export { default as Projects } from "./Projects"
export { default as About } from "./About"
export { default as Education } from "./Education"
export { default as Experience } from "./Experience"
export { default as Contact } from "./Contact"
export { default as Skills } from "./Skills"
export { default as QnAs } from "./QnAs"
